discovery-url: https://accounts.google.com/.well-known/openid-configuration
client-id: 162986408302-tskjmtpi9l8aou75gaefag98bpgar1os.apps.googleusercontent.com
client-secret: dZECtKVKKEVacO3RrckjARHs

listen: 0.0.0.0:443
#listen-http: 0.0.0.0:2016

#enable-refresh-token: true
#enable-encrypted-token: true
#encryption-key: secret
secure-cookie: false

enable-logging: true
enable-json-logging: true
enable-metrics: true
upstream-keepalives: true

enable-https-redirection: true
enable-security-filter: true
use-letsencrypt: true
letsencrypt-cache-dir: /lecache
hostnames:
  - play.monitoringartist.com

#skip-upstream-tls-verify: false
#enable-forwarding: true
#tls-cert value                    path to ths TLS certificate
#tls-private-key value             path to the private key for TLS
#tls-ca-certificate value          path to the ca certificate used for signing requests
tls-ca-certificate: /cacert.pem 
#tls-ca-key value                  path the ca private key, used by the forward signing proxy
tls-ca-key: /cakey.pem
#tls-client-certificate value      path to the client certificate for outbound connections in reverse and forwarding proxy modes
   
redirection-url: https://play.monitoringartist.com/

upstream-url: https://localhost:8082/
#upstream-url: http://volkswagen.com/

resources:
- uri: /*
  methods:
  - GET

