discovery-url: https://accounts.google.com/.well-known/openid-configuration
client-id: 162986408302-tskjmtpi9l8aou75gaefag98bpgar1os.apps.googleusercontent.com
client-secret: dZECtKVKKEVacO3RrckjARHs

listen: 0.0.0.0:2016

#enable-refresh-token: true
secure-cookie: false

enable-logging: true
enable-metrics: true
upstream-keepalives: true

redirection-url: http://play.monitoringartist.com:2016/

upstream-url: http://localhost:8081/
#upstream-url: http://volkswagen.com/

resources:
- uri: /*
  methods:
  - GET
